# Generated by Django 2.2.12 on 2022-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitsTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
